name: Build myPieIDE
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myPieIDE-debug-APK
          path: bin/*.apk

